name: PR - Terraform Doc
on:
  workflow_dispatch:

  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
       ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: ./infa/tf_deploy_landingzone
        output-file: README.md
        output-method: inject
        git-push: "true"
        # recursive: true
        # recursive-path: ../modules

    - name: Render terraform docs
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: ./infa/tf_deploy_network
        output-file: README.md
        output-method: inject
        git-push: "true"
        # recursive: true
        # recursive-path: ../modules

    - name: Render terraform docs
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: ./infa/tf_deploy_subscription
        output-file: README.md
        output-method: inject
        git-push: "true"
        # recursive: true
        # recursive-path: ../modules

    - name: Render terraform docs
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        working-dir: ./infa/tf_deploy_palo
        output-file: README.md
        output-method: inject
        git-push: "true"
        # recursive: true
        # recursive-path: ../modules
