name: Landing Zones

on:
  pull_request:
    branches:
    - main
    paths:
    - 'infa/tf_deploy_landingzone/**'

  workflow_dispatch:

  push:
    branches:
     - main
    paths:
    - 'infa/tf_deploy_landingzone/**'

  workflow_call:

jobs:
  lz1:
    uses: ./.github/workflows/template-terraform-run.yml
    with:
      WORKING_DIR: './infa/tf_deploy_landingzone'
      TF_STATE_FILE: 'landingzone1.tfstate'
      TF_VARS_FILE: 'landingzone1.tfvars'
    secrets:
      TF_STATE_RG: ${{ secrets.TERRAFORM_STATE_RG }}
      TF_STATE_SA: ${{ secrets.TERRAFORM_STATE_SA }}
      TF_STATE_CONTAINER: ${{ secrets.TERRAFORM_STATE_CONTAINER }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

  lz2:
    uses: ./.github/workflows/template-terraform-run.yml
    with:
      WORKING_DIR: './infa/tf_deploy_landingzone'
      TF_STATE_FILE: 'landingzone2.tfstate'
      TF_VARS_FILE: 'landingzone2.tfvars'
    secrets:
      TF_STATE_RG: ${{ secrets.TERRAFORM_STATE_RG }}
      TF_STATE_SA: ${{ secrets.TERRAFORM_STATE_SA }}
      TF_STATE_CONTAINER: ${{ secrets.TERRAFORM_STATE_CONTAINER }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

  lz3:
    uses: ./.github/workflows/template-terraform-run.yml
    with:
      WORKING_DIR: './infa/tf_deploy_landingzone'
      TF_STATE_FILE: 'landingzone3.tfstate'
      TF_VARS_FILE: 'landingzone3.tfvars'
    secrets:
      TF_STATE_RG: ${{ secrets.TERRAFORM_STATE_RG }}
      TF_STATE_SA: ${{ secrets.TERRAFORM_STATE_SA }}
      TF_STATE_CONTAINER: ${{ secrets.TERRAFORM_STATE_CONTAINER }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
    
  lz4:
    uses: ./.github/workflows/template-terraform-run.yml
    with:
      WORKING_DIR: './infa/tf_deploy_landingzone'
      TF_STATE_FILE: 'landingzone4.tfstate'
      TF_VARS_FILE: 'landingzone4.tfvars'
    secrets:
      TF_STATE_RG: ${{ secrets.TERRAFORM_STATE_RG }}
      TF_STATE_SA: ${{ secrets.TERRAFORM_STATE_SA }}
      TF_STATE_CONTAINER: ${{ secrets.TERRAFORM_STATE_CONTAINER }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
  