name: Network - HubSpoke

on:
  pull_request:
    branches:
    - main
    paths:
    - './infa/tf_deploy_network/**'

  workflow_dispatch:

  push:
    branches:
     - main
    paths:
    - './infa/tf_deploy_network/**'

  workflow_call:

jobs:
  net:
    uses: ./.github/workflows/template-terraform-run.yml
    with:
      WORKING_DIR: './infa/tf_deploy_network'
      TF_STATE_FILE: 'network.tfstate'
      TF_VARS_FILE: 'network.tfvars'
    secrets:
      TF_STATE_RG: ${{ secrets.TERRAFORM_STATE_RG }}
      TF_STATE_SA: ${{ secrets.TERRAFORM_STATE_SA }}
      TF_STATE_CONTAINER: ${{ secrets.TERRAFORM_STATE_CONTAINER }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
  